### ISSUE TITLE
Feature: User can view a list of ingredients

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view a list of all ingredients.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

They will have an option to click a button under the main header or click the first icon on the bottom nav bar to view the list of ingredients.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/121099725-38bb4a00-c7ad-11eb-93fc-73f67fe271af.png)
![image](https://user-images.githubusercontent.com/82009814/121099753-45d83900-c7ad-11eb-8917-383294b6a43f.png)
![image](https://user-images.githubusercontent.com/82009814/121099765-4bce1a00-c7ad-11eb-865c-b8a892ee8284.png)
![image](https://user-images.githubusercontent.com/82009814/121099771-4ffa3780-c7ad-11eb-9d55-50754531ffb3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Link FontAwesome library.
- [x] Make the home page with HTML.
  - [x] Have a common title heading for reuse.
  - [x] Have a common nav bar for reuse.
  - [x] Use view-swapping to show ingredients list.
  - [x] Have the display responsive for mobile -> browser.
- [x] Style the HTML elements with CSS.
  - [x] Title header & nav bar will have main color (#66B6D2).
  - [x] Background and text on main color (#FFFEEB).
  - [x] Icon or and selected text (#EAB676).
  - [x] Selected text (#E88000).
  - [x] Alt background (#b2dae8).
  - [x] Text on alt BG (#934D2F).
  - [x] Button selected (#007DA9).
- [x] Query dom elements for 2 buttons, nav bar links and ingredients list.
- [x] Request ingredients list from cocktailDB API.
- [x] Populate ingredients list .
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
