### ISSUE TITLE
Polish: Allow the user to click on a drink panel to see additional drink details

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#15]
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Text on Home page
- [x] Text on Ingredients page
- [x] Text on Categories page
- [x] Text on Search page
- [x] Text on Favorites page
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Show a loading spinner while the app is making requests for data.
- [x] Spell-check and grammar-check all hard-coded text, like buttons, labels, and headings.
- [x] Scrub all undesirable or unrealistic example data if using a database.
- [x] When data fetching or search results lists are empty, show a message informing the user that there were no results found.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile (375px x 812px) and desktop (1280px x 720px) screens.
  - [x] Confirm that resizing the browser window from mobile, to desktop and back does not look "broken" at any point.
  - [x] Create GIFs of the app being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
