### ISSUE TITLE
Feature: User can click on an drink img to see details & recipe

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on an drink img to see details & recipe

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On any page with an image of a drink, the user can click the image to see additional details and recipe for the drink.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In renderDrinkRow( ), add event listener to the drink's img.
  - [x] On 'click', clear the list.
    - [x] getAttribute(drink-id).
    - [x] Make a HTTP Request and search for drink using the ID.
    - [x] call renderDetailedDrink(drink) passing 'xhr.response.drink[0]' into arguments list.
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
