### ISSUE TITLE
Feature: User can view a list of categories

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a list of all categories of drinks and see all drinks with that category name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From any page, the user can go to the 'categories' page. From there, view and choose to click a category to filter all drinks with that category name. They may also press the 'home' icon to go back to the 'home' page or 'ingredients' icon/text to go to the 'ingredients' page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/82009814/121235583-e11eec00-c849-11eb-887c-67538a8c6e2b.png)
![image](https://user-images.githubusercontent.com/82009814/121235619-e5e3a000-c849-11eb-8e55-1e1d26e3f551.png)
![image](https://user-images.githubusercontent.com/82009814/121235644-ec721780-c849-11eb-8e02-a59f01aad53f.png)
![image](https://user-images.githubusercontent.com/82009814/121235697-fbf16080-c849-11eb-8cdc-53327ed3e676.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Structure 'categories' page with HTML & CSS
  - [x] Add a ul to hold list of categories or drinks
  - [x] Do the same for the media query section
- [x] Make the categories buttons go to the 'categories' page
  - [x] Query for categories icon, categories text, and categories ul
  - [x] Add event listeners with callback functions
- [x] GET HTTPSRequest
- [x] Fill 'categories' list and add event listeners for each category
  - [x] A click on a category should clear the list and add a list of all drinks within that category
  - [x] Add drink img & name to each list item
  - [x] Add 'heart' icon for each drink
- **Must Dos**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
