### ISSUE TITLE
Refactor: Render functions: render fx, handle fx, etc.

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#21]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Render functions should only create DOM elements, and return the resulting complete tree.
- [x] Handle functions should take care of page view or element view changes.
- [x] Create handle function for all 'click' events.
- [x] Helper functions will be moved to the bottom of main.js.
- **Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
