### ISSUE TITLE
Polish: UI/UX Polish

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#24]
1. Should be able to click on drink card to open details
2. Back button should be added to drink details to take you back to the list
3. Random drink overflow image problem when vertical size of screen is reduced
4. Add a little space between the nav bubbles on desktop to prevent crowding
5. Reduce Header height on desktop and Cocktail info to grant more space to the drinks below
6. Set a min height for the drink display area to prevent smushing
7. Should be able to remove a favorite by clicking on the heart again
8. Should not be able to add duplicate favorites
9. I would clear the text input on interaction rather than value update
10. Update placeholder to indicate need for click on search input as it looks really cool, but it is not obvious it is an input
11. Remove Click on a picture of a drink for its recipe when there are no results

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Put click event listener on drink card instead of image to open details.
- [x] Add 'back' button to bring user back to list from drink details.
- [x] Make drink images scale vertically.
- [x] Increase margin between nav links on desktop.
- [x] Decrease header heights to make main content more viewable.
- [x] Set a min height for the drink display area to prevent smushing
- [x] Remove from 'favorites' if user presses heart again.
- [x] No duplicate favorites.
- [x] Clear 'search' placeholder on focus instead of active.
- [x] Update placeholder text to more clearly indicate that it is an input box.
- [x] Remove "Click on a picture of a drink for its recipe" when there are no results
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Show a loading spinner while the app is making requests for data.
- [x] Spell-check and grammar-check all hard-coded text, like buttons, labels, and headings.
- [x] Scrub all undesirable or unrealistic example data if using a database.
- [x] When data fetching or search results lists are empty, show a message informing the user that there were no results found.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile (375px x 812px) and desktop (1280px x 720px) screens.
  - [x] Confirm that resizing the browser window from mobile, to desktop and back does not look "broken" at any point.
  - [x] Create GIFs of the app being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
