### ISSUE TITLE
Refactor: Convert to ES6

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#26]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Convert all var variables to let or const
- [x] Convert functions to arrow functions where appropriate
- **Must Do's**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
