### ISSUE TITLE
Feature: User can search for a drink by name

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can see a list of drink that contains an inputted string.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
From any screen, the user can click a link to go to the 'search' page. From the 'search' page, the user can search for a drink by inputting a string.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/121103350-a159f500-c7b4-11eb-8385-a1b1c3704135.png)
![image](https://user-images.githubusercontent.com/82009814/121103364-a6b73f80-c7b4-11eb-9826-892f874f4898.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a 'hidden' text input into the main-header.
  - [x] Style the input. 
  - [x] Add a message to tell user to press 'enter' to start search
- [x] Add event listener onto input to extract the value from user input.
- [x] Listen for 'keydown' event on document to start search on 'enter'
- [x] Make a new HTTPS request for all drinks with the string input.
- [x] Render the list of drinks.
- **Must do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
