### ISSUE TITLE
Feature: User can filter drink by ingredient

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a list of drinks that are made with a specific ingredient.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'ingredients' page, the user can click on an ingredient and a list will appear with all drinks that contain that ingredient.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/82009814/121103484-e4b46380-c7b4-11eb-82c5-6d260fefe1bf.png)
![image](https://user-images.githubusercontent.com/82009814/121103491-e9791780-c7b4-11eb-8714-c12ef672bdf7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add event listeners for each ingredient in 'ingredients' list.
  - [x] GET HTTP request for list of drinks filtered by the ingredient that was clicked.
  - [x] Render a list of drinks that contain that ingredient.
- [x] Make sure all pages reset back to original state.
- **Must do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
