### ISSUE TITLE
Feature: User can click to see a random drink with recipe

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can see a random drink with description and recipe.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'home' page, the user can click the icon and see a page with a single drink with description and recipe. A new button will appear and on click, a new random drink will show up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/121103626-2cd38600-c7b5-11eb-8f3b-a05616d49808.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add text below the home page icon: "Click here to see a random recipe!".
- [x] Add a new 'hidden' button underneath the secondary page ul & style it.
  - [x] Include a new 'hidden' div above the new button to hold the drinks' details. 
- [x] Add an event listener to the home page icon and to the button.
  - [x] Write a callback function for both event listeners (they call the same function).
- [x] GET HTTP request for a random drink & grab the appropriate data.
- [x] Render a detailed drink profile
  - [x] Mobile view:
    - [x] Drink img spans width on top
    - [x] Drink name under img
    - [x] Drink Ingredients & Drink recipe in the same div (flex-direction: column)
  - [x] Browser view:
    - [x] Show secondary header and make text content = the drink's name.
    - [x] Drink img below name.
    - [x] Drink ingredients (left) & Drink recipe (right) under img in the same div. (direction: row)
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
