### ISSUE TITLE
Feature: User can save a drink to their 'favorites' list

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can add any drink to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From any page that includes a drink, the user can click the heart icon to add it to their 'favorites'.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/121103748-699f7d00-c7b5-11eb-8de1-e6ee3ce161f9.png)
![image](https://user-images.githubusercontent.com/82009814/121103767-70c68b00-c7b5-11eb-82a9-75946a78239e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Declare an array literal in data.js to hold a list of favorite drink objects.
- [x] Add 'click' event listeners to all 'hearts'.
  - [x] When clicked, add the drink to favorite drinks array.
- [x] Save data.js to localStorage.
- [x] Add 'click' event listener to 'favorites' icon/text.
  - [x] When clicked, render favorite drinks list from array & change icon/text to 'selected' color.
- [x] Make sure favorites list is cleared when clicking to another page.
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
