### ISSUE TITLE
Feature: User can delete a drink from their favorites 

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can remove any drink from their 'favorites'.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'favorites' page, the user can click the trash can icon to delete a drink.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/121103858-a10e2980-c7b5-11eb-8df5-63d381061c96.png)
![image](https://user-images.githubusercontent.com/82009814/121103866-a4091a00-c7b5-11eb-9a42-52495cd742de.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the 'favorites' page, replace all 'heart' icons with 'trash can' icons.
- [x] Add event listeners to all 'trash can' icons.
  - [x] Open up a small model for confirmation ("Are you sure?" Yes | Cancel).
  - [x] On 'Yes', get the idDrink of the drink that user wants to delete. On 'Cancel', close model.
  - [x] Splice the drink from favoriteDrinks array.
  - [x] Make sure 'favorites' list is updated on 'Yes'.
- [x] Make sure drinks-local-storage is updated.
- **Must Do's**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
